version: '3.8'
services:
  app:
    restart: always
    build:
      context: .
    volumes:
      - .:/app
    environment:
      MYSQL_DATABASE: app_development
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      DB_HOST_NAME: db
    # command: sh -c "rm -f tmp/pids/server.pid && rails s -b 0.0.0.0 -p 3000"
    ports:
      - 3000:3000
    # depends_on:
    #   - db
  # db:
  #   restart: always
  #   image: mysql:8.0.25
  #   platform: linux/amd64
  #   environment:
  #     MYSQL_DATABASE: app_development
  #     MYSQL_USER: ${MYSQL_USER}
  #     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  #     MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  #     TZ: 'Asia/Tokyo'
  #     MYSQL_ROOT_HOST: "%"
  #   tty: true
  #   command: mysqld --character-set-server=utf8mb4 --explicit_defaults_for_timestamp=true --default-authentication-plugin=mysql_native_password
  #   ports:
  #     - 3306:3306